#!/usr/bin/env node

/**
 * AttendPro Automated Deployment Script
 * This script helps automate the deployment process to various platforms
 */

const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');

console.log('🚀 AttendPro Automated Deployment Script');
console.log('=========================================\n');

// Generate a secure session secret
function generateSessionSecret() {
    const crypto = require('crypto');
    return crypto.randomBytes(64).toString('hex');
}

// Create environment variables template
function createEnvTemplate() {
    const sessionSecret = generateSessionSecret();
    
    const envContent = `# AttendPro Production Environment Variables
# Generated by automated deployment script

NODE_ENV=production
PORT=3000
SESSION_SECRET=${sessionSecret}
TRUST_PROXY=true
FORCE_HTTPS=true
ENABLE_COMPRESSION=true
CACHE_STATIC_FILES=true
ENABLE_REGISTRATION=false
ENABLE_QR_CODE_GENERATION=true
ENABLE_BULK_OPERATIONS=true
LOG_LEVEL=warn
LOG_TO_FILE=true
RATE_LIMIT_MAX_REQUESTS=100
AUTH_RATE_LIMIT_MAX=5
ADMIN_RATE_LIMIT_MAX=3
DB_MAINTENANCE_ENABLED=true

# You need to add these manually:
# MONGODB_URI=mongodb+srv://username:password@cluster.mongodb.net/attendpro
# BASE_URL=https://your-app-name.up.railway.app (or vercel.app)
`;

    fs.writeFileSync('.env.production', envContent);
    console.log('✅ Created .env.production with secure session secret');
    return sessionSecret;
}

// Display deployment options
function displayDeploymentOptions() {
    console.log('Available deployment platforms:');
    console.log('1. Railway (Recommended)');
    console.log('2. Vercel (Serverless)');
    console.log('3. Generate deployment files only');
    console.log('4. Local setup for testing\n');
}

// Railway deployment instructions
function railwayDeploy() {
    console.log('🚂 Railway Deployment Process:');
    console.log('================================');
    console.log('1. Go to https://railway.app');
    console.log('2. Sign in with GitHub');
    console.log('3. Click "Deploy from GitHub repo"');
    console.log('4. Select "AbdullahAnsari103/ATTENDPRO"');
    console.log('5. Add these environment variables in Railway dashboard:');
    console.log('');
    
    const envContent = fs.readFileSync('.env.production', 'utf8');
    console.log(envContent);
    
    console.log('6. Also add:');
    console.log('   MONGODB_URI=mongodb+srv://username:password@cluster.mongodb.net/attendpro');
    console.log('   BASE_URL=https://your-app.up.railway.app\n');
    
    console.log('🗄️ MongoDB Atlas Setup:');
    console.log('1. Go to https://mongodb.com/atlas');
    console.log('2. Create free cluster');
    console.log('3. Create database user');
    console.log('4. Set IP whitelist to 0.0.0.0/0');
    console.log('5. Get connection string\n');
}

// Vercel deployment
function vercelDeploy() {
    console.log('▲ Vercel Deployment Process:');
    console.log('=============================');
    console.log('To deploy to Vercel, you need to:');
    console.log('1. Run: vercel login');
    console.log('2. Run: vercel --prod');
    console.log('3. Set environment variables in Vercel dashboard');
    console.log('');
    
    const envContent = fs.readFileSync('.env.production', 'utf8');
    console.log('Environment variables needed:');
    console.log(envContent);
}

// Create deployment files
function createDeploymentFiles() {
    console.log('📁 Creating deployment configuration files...\n');
    
    // Create Procfile for Railway/Heroku
    const procfileContent = 'web: npm start';
    fs.writeFileSync('Procfile', procfileContent);
    console.log('✅ Created Procfile');
    
    // Create railway.json
    const railwayConfig = {
        "deploy": {
            "startCommand": "npm start",
            "healthcheckPath": "/health"
        }
    };
    fs.writeFileSync('railway.json', JSON.stringify(railwayConfig, null, 2));
    console.log('✅ Created railway.json');
    
    // Update package.json scripts if needed
    const packageJson = JSON.parse(fs.readFileSync('package.json', 'utf8'));
    if (!packageJson.scripts['railway:start']) {
        packageJson.scripts['railway:start'] = 'NODE_ENV=production node index.js';
        fs.writeFileSync('package.json', JSON.stringify(packageJson, null, 2));
        console.log('✅ Updated package.json scripts');
    }
    
    console.log('✅ All deployment files created!\n');
}

// Local setup
function localSetup() {
    console.log('💻 Setting up for local development...\n');
    
    // Update .env for local development
    let envContent = fs.readFileSync('.env', 'utf8');
    envContent = envContent.replace('NODE_ENV=production', 'NODE_ENV=development');
    envContent = envContent.replace('MONGODB_URI=mongodb+srv://username:password@cluster.mongodb.net/attendpro', 
                                  'MONGODB_URI=mongodb://localhost:27017/attendpro');
    fs.writeFileSync('.env.local', envContent);
    console.log('✅ Created .env.local for local development');
    
    console.log('To run locally:');
    console.log('1. Install MongoDB locally or use MongoDB Atlas');
    console.log('2. Copy .env.local to .env');
    console.log('3. Update MONGODB_URI in .env');
    console.log('4. Run: npm run dev\n');
}

// Main execution
async function main() {
    try {
        console.log('Preparing deployment...\n');
        
        // Create environment template
        const sessionSecret = createEnvTemplate();
        
        // Create deployment files
        createDeploymentFiles();
        
        // Display options
        displayDeploymentOptions();
        
        // Show Railway instructions (recommended)
        railwayDeploy();
        
        console.log('🎉 Deployment preparation complete!');
        console.log('=======================================');
        console.log('Your AttendPro application is ready for deployment.');
        console.log('All necessary configuration files have been created.');
        console.log('');
        console.log('Quick Deploy Options:');
        console.log('• Railway (Recommended): Follow the Railway instructions above');
        console.log('• Vercel: Run "vercel --prod" after logging in');
        console.log('• Local: Use the local setup files created');
        console.log('');
        console.log('Emergency Admin Credentials:');
        console.log('• Username: admin');
        console.log('• Password: AttendPro2024!');
        console.log('• Remove these after creating your permanent admin account');
        
    } catch (error) {
        console.error('❌ Error during deployment preparation:', error.message);
        process.exit(1);
    }
}

// Run the script
main();
